spring:
  datasource:
    url: jdbc:h2:mem:account_service_db
    driverClassName: org.h2.Driver
    username: user
    password: password

flyway:
  user: user
  password: password
  schemas: account_service_db
  url: jdbc:h2:mem:account_service_db
  locations: filesystem:src/main/resources/db/migration/

server:
  port: 8090

client:
  transaction-management:
    url: http://localhost:8080
